const OK = 200;
const CREATED = 201;
const ACCEPTED = 202;
const NO_CONTENT = 204;
const BAD_REQUEST = 400;
const UNAUTHORIZED = 401;
const FORBIDDEN = 403;
const NOT_FOUND = 404;
const METHOD_NOT_ALLOWED = 405;
const REQUEST_TIMEOUT = 408;
const LENGTH_REQUIRED = 411;
const REQUEST_TOO_LONG = 413;
const REQUEST_URI_TOO_LONG = 414;
const UNSUPPORTED_MEDIA_TYPE = 415;
const TOO_MANY_REQUESTS = 429;
const INTERNAL_SERVER_ERROR = 500;
const BAD_GATEWAY = 502;
const SERVICE_UNAVAILABLE = 503;
const GATEWAY_TIMEOUT = 504;
const INSUFFICIENT_STORAGE = 507;
const UNPROCESSABLE_ENTITY = 422;

module.exports = {
	OK,
	CREATED,
	ACCEPTED,
	NO_CONTENT,
	BAD_REQUEST,
	UNAUTHORIZED,
	FORBIDDEN,
	NOT_FOUND,
	METHOD_NOT_ALLOWED,
	REQUEST_TIMEOUT,
	LENGTH_REQUIRED,
	REQUEST_TOO_LONG,
	REQUEST_URI_TOO_LONG,
	UNSUPPORTED_MEDIA_TYPE,
	TOO_MANY_REQUESTS,
	INTERNAL_SERVER_ERROR,
	BAD_GATEWAY,
	SERVICE_UNAVAILABLE,
	GATEWAY_TIMEOUT,
	INSUFFICIENT_STORAGE,
	UNPROCESSABLE_ENTITY,
};
